### PR TITLE
it looks better and we have programming now 

### PR DESCRIPTION
**Pull request by sudocode1**

### CODE REVIEW

**Comment by jbmagination** [comment]
cool! i'm gonna get rid of the programming part at the end but besides that yes this looks good :D

**Comment by sudocode1** [comment]
pog

**Comment by jbmagination** [comment]
ok now i realize you literally only did programming part

ok ill revise that part then

**Comment by sudocode1** [comment]
no i added some other stuff

**Comment by sudocode1** [comment]
the whole text box things are now span tags

**Pull request merged**
